In [6]:
from scipy.signal import residuez
import numpy as np

from functions.deconv_m import deconv_m

P4.10

In [7]:
nb = np.arange(-2, 4)
b = np.array([1, 1, 1, 1, 1, 1])
na = np.arange(-1, 2) 
a = np.array([1, 2, 1])

# Run the function
p, np, r, nr = deconv_m(b, nb, a, na)

print(p)
print(np)
print(r)
print(nr)

[ 1. -1.  2. -2.]
[-1  0  1  2]
[0. 0. 0. 0. 3. 3.]
[-2 -1  0  1  2  3]


P4.11

In [28]:
b1 = [1,-1,-4,4] 
a1 = [1,-11/4,13/8,-1/4]

r1,p1,k1 = residuez(b1,a1)

print(r1)
print(p1)
print(k1)

[ 2.70000000e+01 -1.00000000e+01 -1.62409768e-14]
[0.25 0.5  2.  ]
[-16.]


In [29]:
b2 = [1,1,-4,4] 
a2 = [1,-11/4,13/8,-1/4]

r2,p2,k2 = residuez(b2,a2)

print(r2)
print(p2)
print(k2)

[ 28.14285714 -12.66666667   1.52380952]
[0.25 0.5  2.  ]
[-16.]


In [30]:
b3 = [1,-3,4,1] 
a3 = [1,-4,1,-0.16]

r3,p3,k3 = residuez(b3,a3)

print(r3)
print(p3)
print(k3)

[3.35587219+5.76587594j 3.35587219-5.76587594j 0.53825562+0.j        ]
[0.1278287 +0.16245294j 0.1278287 -0.16245294j 3.74434261+0.j        ]
[-6.25]


In [35]:
b4 = [0,0,1] 
a4 = [1,2,1.25,0.25]

r4,p4,k4 = residuez(b4,a4)

print(r4)
print(p4)
print(k4)

[ 3.55271368e-15-0.j -4.00000000e+00+0.j  4.00000000e+00+0.j]
[-0.5+0.j -0.5+0.j -1. +0.j]
[]


In [36]:
b5 = [0,0,0,1]
a5 = np.convolve([1,0,-0.25],[1,0,-0.25])

r5,p5,k5 = residuez(b5,a5)

print(r5)
print(p5)
print(k5)

[-4.+0.j  2.+0.j  4.+0.j -2.+0.j]
[ 0.5+0.j  0.5+0.j -0.5+0.j -0.5+0.j]
[]
